### ISSUE TITLE
feat request: fallback pipe for missing emojis

### ISSUE THREAD

**Issue by somq** [ahkohd/ngx-emoj#2]
Hi there,

It appears that some emoji are missing on some devices.

![missing emojis](https://i.imgur.com/afkAf7b.png)

On your picker repo you implemented a fallback pipe, which might be able to fill the gap, though the [detector](https://github.com/ahkohd/ngx-emoji-picker/blob/master/projects/ngx-emoji-picker/src/lib/pipes/emoji-fallback.pipe.ts#L18) fails to detect properly missing emojis.

Would that be possible to add the same fallback pipe on this repo?   

As [you stated](https://github.com/ahkohd/ngx-emoji-picker/issues/77), the picker repo is in maintenance mode, and at it's state is not suitable Ionic production  apps for slow render reasons.  
Just my 2 cents but I think this repo would be enough for both usecases; mobile & desktop apps, if it can handle somewhat old mobile devices and the fallback is then a main concern.

I suggest to use `if-emoji` lib or [their implementation](https://github.com/Dafrok/if-emoji/blob/master/src/index.js) for the detector.

Currently, I use this simple pipe on my project for the fallback and it works with no false positive so far

```ts
import { Pipe, PipeTransform } from '@angular/core';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import ifEmoji from 'if-emoji'
import twemoji from 'twemoji';

@Pipe({
  name: 'emojiFallback'
})
export class EmojiFallbackPipe implements PipeTransform {

  constructor(private domSanitizer: DomSanitizer) { }

  transform(emoji: string): string | SafeHtml {
    return ifEmoji(emoji) ? emoji : this.domSanitizer.bypassSecurityTrustHtml(twemoji.parse(emoji.trim()));
  }
}
```

If you need some help or a PR, please let me know.

**Comment by ahkohd** [comment]
Hi, @somq I'm sorry for the late reply.

This is fantastic, can you make a PR that will introduce this feature?

**Comment by ahkohd** [comment]
Thanks, @somq  for adding this fix. I'll update the NPM package as soon as possible.
