### ISSUE TITLE
Override default css

### ISSUE THREAD

**Issue by naonvl** [ahkohd/ngx-emoj#4]
Hi thanks for the amazing plugin, i want to add this to my angular apps which installed on my wordpress. but the ui look like this

![image](https://user-images.githubusercontent.com/43715306/117435976-a4b15500-af58-11eb-9896-c251db9c768d.png)

the icon looks so small, but if i dont use it on wordpress it works fine, how to change that using css?

**Comment by ahkohd** [comment]
Hi, @naonvl I apologise for the late response. Have you found a solution?

**Comment by naonvl** [comment]
i forgot you have theme attribute, really helpful thanks

**Comment by ahkohd** [comment]
I'm glad you find it useful
